# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
#%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print( np.__version__ )
np.show_config()

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros( 10 )

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
v = np.zeros( 10 )
v.nbytes


80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.info( 'add' )

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is creat

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
v = np.zeros( 10 )
v[ 4 ] = 1
print( v )

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
v = np.arange(10,50)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
v[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
np.nonzero( [1,2,0,0,4,0] )

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
np.eye( 3 )

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
np.random.random( ( 3, 3, 3 ) )

array([[[0.09347405, 0.44881033, 0.08669458],
        [0.67141924, 0.88146603, 0.54951883],
        [0.86509769, 0.2120585 , 0.46814364]],

       [[0.41101787, 0.15724   , 0.50614489],
        [0.77357862, 0.12845646, 0.92008497],
        [0.29765026, 0.11924229, 0.33354773]],

       [[0.54144398, 0.50392344, 0.75903968],
        [0.16164988, 0.57561709, 0.87127999],
        [0.58292891, 0.32989239, 0.3548125 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
v = np.random.random( ( 10, 10 ) )
v.max(), v.min()

(0.9932053714840228, 0.0040278745687306605)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
np.random.random( 30 ).mean()

0.466528229118109

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
v = np.ones((4,4))
v[1:-1,1:-1] = 0
v

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
v = np.random.random((4,4,4))
np.pad(v, pad_width=1, mode='constant', constant_values=0)


array([[[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]],

       [[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.70374456, 0.23172793, 0.71669722, 0.58340206,
         0.        ],
        [0.        , 0.24136726, 0.3235615 , 0.10771093, 0.12496565,
         0.        ],
        [0.        , 0.06086687, 0.77845612, 0.10963104, 0.79936052,
         0.        ],
        [0.        , 0.5154501 , 0.49093864, 0.09846037, 0.98638877,
         0.        

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
# 0 * np.nan --- nan
# np.nan == np.nan --- False
# np.inf > np.nan --- False
# np.nan - np.nan --- nan
# np.nan in set ([np.nan]) --- True
# 0.3 == 3 * 0.1 --- False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
np.diag(1+np.arange(4), -1 )

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
V = np.zeros((8,8),dtype=int)
V[1::2,0::2] = 1
V[0::2,1::2] = 1
V


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
np.unravel_index(99,(6,7,8))
#np.zeros((6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
#np.info( 'tile' )
#np.info( 'identity')
np.tile( np.eye(2), (4,4) )

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
v = np.random.random((5,5))
(v - v.mean())/v.std()

array([[ 1.39564331, -0.8269557 ,  1.23692874, -0.41986064, -1.13957601],
       [-1.18289069,  1.47489434, -0.60735432,  0.11341801,  0.97063865],
       [-1.14432814,  1.26457035,  0.17405737, -1.15981558, -1.12690654],
       [-0.74117621, -0.30751617, -1.13907332,  1.29976901,  0.02985963],
       [-1.13487148,  1.55727927, -0.10670832,  1.20702749,  0.31294693]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])
#np.info('dtype')

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
np.dot( np.ones((5,3)), np.ones((3,2)) )
np.ones((5,3)) @ np.ones((3,2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
v = np.arange(1, 10)
v[(3 < v) & (v < 8)] *= -1
v


array([ 1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print( sum(range(5),-1) )
#from numpy import *
np.sum(range(5))#,-1)
#np.info( 'sum')

9


10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
z = np.arange(3, 6)
print( z ) 
print( z**z )
print( 2 << z )
print( 2 << z >> 2 )
print( z <- z )
print( 1j*z )
print( z/1/1 )
# z<z>z -- error

[3 4 5]
[  27  256 3125]
[16 32 64]
[ 4  8 16]
[False False False]
[0.+3.j 0.+4.j 0.+5.j]
[3. 4. 5.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
# np.array(0) / np.array(0) -- RuntimeWarning - nan
# np.array(0) // np.array(0) -- RutimeWarning - 0
np.array([np.nan]).astype(int).astype(float) # array([-9.22337204e+18])

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
v = np.random.uniform(-10,+10,10)
np.copysign(np.ceil(np.abs(v)), v)
#np.where(v>0, np.ceil(v), np.floor(v))

array([ 1., -8., -5., -6.,  1., -1., -8.,  2.,  2.,  2.])

#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
np.intersect1d(np.random.randint(1, 10, (10,3)), np.random.randint(1,10,10))
#np.random.randint(1,10,(10,10))


array([1, 3, 4, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
# Suicide mode on
defaults = np.seterr(all="ignore")
print( np.ones(1) / 0 )

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    print( np.arange(3) / 0 )


[inf]
[nan inf inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
#np.info('emath')
with np.errstate(all="ignore"):
    print( np.sqrt(-1) == np.emath.sqrt(-1) ) 
#False, but with Warning

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
#np.info('date')
print( np.datetime64('today') - 1 )
print( np.datetime64('today') )
print( np.datetime64('today') + 1 )
#np.today()

2023-03-30
2023-03-31
2023-04-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
#np.info('datetime64')
#[ np.datetime64('2016-07-01') + i for i in range(20) ]
#a = [np.datetime64('2016-07-01'):np.datetime64('2016-08-01')]
#[ i for i in range(np.datetime64('2016-07-01'), np.datetime64('2016-08-01')) ]
np.arange('2016-07', '2016-08', dtype='datetime64[D]')


array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A = np.array([1,2,3], dtype='float64')
B = np.array([-1,-2,0], dtype='float64')
np.add(A,B,out=B)
np.divide(A,2.0,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-0. , -0. , -4.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [36]:
v = np.random.random((3,4)) * 10

print( v )
print( np.array(v, dtype='int64') )
print( np.floor(v) )
print( v.astype(int) )
#print( np.integer(v) )
#np.info('integer')
#np.info('random_sample')

[[0.25852094 7.42820007 6.9767076  7.27299405]
 [8.28321917 6.58147888 6.64626326 5.70072764]
 [6.13187349 4.2301078  7.52763473 0.71880214]]
[[0 7 6 7]
 [8 6 6 5]
 [6 4 7 0]]
[[0. 7. 6. 7.]
 [8. 6. 6. 5.]
 [6. 4. 7. 0.]]
[[0 7 6 7]
 [8 6 6 5]
 [6 4 7 0]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
#np.random.random((5,5)) * 4
np.tile(np.arange(5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [38]:
np.array([np.random.random() for i in range(10)])

array([0.74520701, 0.87234673, 0.85192471, 0.46962169, 0.39991452,
       0.91937874, 0.89299375, 0.20144012, 0.47613807, 0.28786286])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
np.linspace(0,1,11,endpoint=False)[1:]
#np.info('linspace')

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [40]:
v = np.random.random(10)
v.sort()
v

array([0.02490697, 0.07295954, 0.109086  , 0.14230636, 0.15676317,
       0.19890148, 0.20467523, 0.43349255, 0.48974872, 0.55561044])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [41]:
np.add.reduce(np.random.random(20))
#np.info('add')

9.164019266289785

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [42]:
np.allclose(np.random.random((3,4)), np.random.random((3,4)))

False

#### 43. Make an array immutable (read-only) (★★☆)

In [43]:
#np.info('immutable')
v = np.ones(4)
v.flags.writeable = False
#v[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [44]:
v = np.random.random((10,2)) * 10
print( v )
v[:,0], v[:,1] = np.sqrt(v[:,0]**2+v[:,1]**2), np.arctan2(v[:,0], v[:,1])
v

[[3.86530942 7.42849941]
 [9.08164556 6.49850148]
 [7.79617026 6.78519131]
 [6.13691479 0.89530051]
 [5.08324277 8.8317781 ]
 [2.32773112 8.06250176]
 [6.50977893 5.3804004 ]
 [0.38306544 7.19989644]
 [5.10018486 8.1142506 ]
 [3.475171   7.47817828]]


array([[ 8.37396086,  0.47978308],
       [11.16722023,  0.94970071],
       [10.33533221,  0.85462103],
       [ 6.20187764,  1.42593057],
       [10.19017475,  0.52225712],
       [ 8.39179759,  0.2810678 ],
       [ 8.44546803,  0.8800982 ],
       [ 7.2100796 ,  0.05315418],
       [ 9.58399438,  0.56114564],
       [ 8.24620905,  0.43501775]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [45]:
v = np.random.random(10)
#np.info('max')
print( v )
v[ v.argmax() ] = 0
v

[0.30228975 0.88764309 0.64733302 0.04080882 0.5170663  0.01593839
 0.69578199 0.72967142 0.68998378 0.0099026 ]


array([0.30228975, 0.        , 0.64733302, 0.04080882, 0.5170663 ,
       0.01593839, 0.69578199, 0.72967142, 0.68998378, 0.0099026 ])


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [46]:
Z = np.zeros((4,4), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,4),
                             np.linspace(0,1,4))
Z
#v = np.arange(11) / 10
#np.transpose([np.tile(v,len(v)), np.repeat(v, len(v))])

array([[(0.        , 0.        ), (0.33333333, 0.        ),
        (0.66666667, 0.        ), (1.        , 0.        )],
       [(0.        , 0.33333333), (0.33333333, 0.33333333),
        (0.66666667, 0.33333333), (1.        , 0.33333333)],
       [(0.        , 0.66666667), (0.33333333, 0.66666667),
        (0.66666667, 0.66666667), (1.        , 0.66666667)],
       [(0.        , 1.        ), (0.33333333, 1.        ),
        (0.66666667, 1.        ), (1.        , 1.        )]],
      dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [218]:
#x = np.random.random(3) * 10
#y = np.random.random(3) * 10

x = np.arange(start = 2, stop = 6)
#np.info('arange')
y = np.ones(5)
#np.array( [  1/(x[i] - y[:]) for i in range( len( x ) ) ] )
1/(np.atleast_2d(x).T - np.atleast_2d(y))


array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.5       , 0.5       , 0.5       , 0.5       , 0.5       ],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.25      , 0.25      , 0.25      , 0.25      , 0.25      ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [48]:
#np.info('max')
#np.ma.maximum_fill_value(float)
#np.info('maximum_fill_value')
#print( np.ma.maximum_fill_value(1) )

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [49]:
#np.info('set_printoptions')

np.set_printoptions(threshold=np.sys.maxsize)
print( np.zeros((40,40)) )
np.set_printoptions(threshold=10)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
v = np.random.random(10) * 10
el = np.random.random() * 10
print( v )
print( el )
print( np.argmin( (v[:] - el)**2 ) )



[9.1574376  2.64402499 6.23082269 5.93084557 6.82728758 9.0118639
 1.73390864 8.97279718 0.92243293 0.75653237]
6.667015217391244
4


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [51]:
#np.info('array')
np.array(0, dtype = [('pos', [('x', float),
                               ('y', float)]),
                      ('color', [('r', float),
                                 ('g', float),
                                 ('b', float)])])


array(((0., 0.), (0., 0., 0.)),
      dtype=[('pos', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [54]:
#np.info('atleast_2d')
#v = np.arange(5)
#x = np.atleast_2d(v)
#x - x.T



v = np.random.random((100,2))*10

print(v)
x,y = np.atleast_2d(v[:,0], v[:,1])
np.sqrt( (x-x.T)**2 + (y-y.T)**2)





[[4.58603098 2.61978269]
 [0.17462669 5.10418661]
 [1.59062038 7.63397626]
 ...
 [0.87260955 8.62664476]
 [0.57123385 4.66602103]
 [0.19611514 4.0243586 ]]


array([[0.        , 5.06287967, 5.84077237, ..., 7.0620033 , 4.50618323,
        4.6091425 ],
       [5.06287967, 0.        , 2.89911604, ..., 3.59094577, 0.59100449,
        1.08004179],
       [5.84077237, 2.89911604, 0.        , ..., 1.2251246 , 3.13813753,
        3.8696233 ],
       ...,
       [7.0620033 , 3.59094577, 1.2251246 , ..., 0.        , 3.97207347,
        4.65173973],
       [4.50618323, 0.59100449, 3.13813753, ..., 3.97207347, 0.        ,
        0.74326625],
       [4.6091425 , 1.08004179, 3.8696233 , ..., 4.65173973, 0.74326625,
        0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [53]:
Z = (np.random.rand(10)*100).astype(np.float32)
print( Z )
Y = Z.view(np.int32)
print( Y )
Y[:] = Z
print(Y)


[44.76724  31.357662  8.324084 67.04636  17.931093  8.326309 20.261755
 64.83244  95.81706  83.06499 ]
[1110643111 1106959486 1090858867 1116084156 1099920097 1090861200
 1101142035 1115793974 1119855190 1118183750]
[44 31  8 67 17  8 20 64 95 83]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [55]:
from io import StringIO
# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int64)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [56]:
#np.info('enumerate')
#np.enumerate(np.random.random((5,5)))
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
#for index in np.ndindex(Z.shape):
#    print(index, Z[index])


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [57]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 ...
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [58]:
n = 3
p = 3
Z = np.zeros((n,n))

np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

#np.info('choice')
#np.info('put')

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [59]:
k = 3
#X = np.arange(k * k * k).reshape((k,k,k))
#print(X)
#X.mean(axis=(2))#, keepdims=True)
#np.info('mean')
X = np.arange(k * k).reshape((k,k))
print(X)
X - X.mean(axis=1).reshape(1,k).T

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

#### 59. How to sort an array by the nth column? (★★☆)

In [60]:
n = 3
X = np.random.rand(4,4)
#X[:,n].sort()
#X
print(X)
X[:,n].argsort()
#np.info('sort')
#np.info('argsort')

[[0.33809331 0.40135811 0.92614649 0.74853931]
 [0.92358307 0.7115043  0.37727974 0.93451326]
 [0.30683162 0.8491931  0.02898005 0.16518947]
 [0.54174301 0.31950664 0.3512847  0.96904142]]


array([2, 0, 1, 3])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [61]:
# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))


True
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [62]:
Z = np.random.uniform(0,1,10)
val = 0.5
#np.info('flat')
m = Z.flat[((Z - val)**2).argmin()]
print(m)


0.5481338906867225


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [63]:

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B, None])
for x,y,z in it: z[...] = x + y
#[x + y for x,y,z in it]
#np.info('nditer')
print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [64]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [65]:

Z = np.zeros(5)
I = np.random.randint(0,len(Z),7)
print(I)
#Z += np.bincount(I, minlength=len(Z))
#print(Z)


Z = np.zeros(5)
np.add.at(Z, I, 1)
print(Z)

#Z = np.zeros(5)
#Z[I[:]] += 1
#print(Z)


[4 4 0 0 1 1 3]
[2. 2. 0. 1. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [66]:
X = [1,2,3,4,5,6]
I = [1,3,5,3,4,1]
#F = np.bincount(I,X)
#print(F)
[X[I[i]] for i in range(len(I))]
#np.info('bincount')

[2, 4, 6, 4, 5, 2]

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [67]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)


64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [68]:
a = np.arange(2**4).reshape(2,2,2,2)
#np.info('sum')
#a[:,:]
print(a)
a.sum((-1,-2), keepdims=True)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


array([[[[ 6]],

        [[22]]],


       [[[38]],

        [[54]]]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [69]:
#D = np.random.uniform(0,1,100)
#S = np.random.randint(0,10,100)
D = np.array([1,2,3])
S = [[1,1,1],[2,2,2], [0,2,2,2]]
#S = np.array([[1,1,1],[2,2,2]])#,[0,2,2,2]], dtype=object)
#D[S[:]].mean(axis=len(S)-1)
[ D[ np.array(V) ].mean() for V in S ]

#np.info('slice')
#D_sums = np.bincount(S, weights=D)
#D[np.array(S[:], dtype=int)].mean(axis=len(S)-1)
#D_counts = np.bincount(S)
#D_means = D_sums / D_counts
#print(D_means)


[2.0, 3.0, 2.5]

#### 69. How to get the diagonal of a dot product? (★★★)

In [70]:
np.dot( np.arange(4).reshape(4,1), np.arange(4).reshape(1,4) ).diagonal()

array([0, 1, 4, 9])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [71]:
A = np.zeros(17)
A[::4] = np.arange(1,6)[:]
np.set_printoptions(threshold=np.sys.maxsize)
print(A)
np.set_printoptions(threshold=10)
#np.info('put')

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [72]:
#np.info('arange')

#np.arange(5*5*3).reshape((5,5,3)) * np.arange(5*5).reshape((5,5))[...,None]
np.arange(2*2*3).reshape((2,2,3)) * np.arange(2*2).reshape((2,2))[...,None]

array([[[ 0,  0,  0],
        [ 3,  4,  5]],

       [[12, 14, 16],
        [27, 30, 33]]])

#### 72. How to swap two rows of an array? (★★★)

In [73]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [74]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


[( 0,  2) ( 0, 11) ( 2, 11) ... (67, 83) (77, 81) (83, 92)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [75]:
C = np.bincount([1,2,2,3,4,1,1])
A = np.repeat(np.arange(len(C)), C)
A

array([1, 1, 1, 2, 2, 3, 4])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [76]:
Z = np.random.randint(1, 20, 5)
print(Z)
print(np.lib.stride_tricks.sliding_window_view(Z, window_shape=3).mean(axis=-1))


[11 19 12 19 13]
[14.         16.66666667 14.66666667]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [77]:
#Z = np.arange(9)
#Z.reshape((3,len(Z)//3))
Z = np.arange(10)
np.lib.stride_tricks.sliding_window_view(Z, window_shape=3)


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       ...,
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [78]:
Z = np.random.randint(0,2,5)
print(Z)
print(np.logical_not(Z, out=Z))

Z = np.random.uniform(-1.0,1.0,5)
print(Z)
np.negative(Z, out=Z)


[0 1 0 1 1]
[1 0 1 0 0]
[-0.06539845  0.88726779 -0.85203187 -0.88707881 -0.74859679]


array([ 0.06539845, -0.88726779,  0.85203187,  0.88707881,  0.74859679])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [79]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))
    

[ 1.93458958  7.22970632  7.70839571  0.5072545   6.3684017   9.07704935
  0.54652726  4.08120629  4.00716604 15.85282174]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [80]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))


[[ 3.87196302  3.18419118 14.81908872 ...  7.34034464  4.23770652
   7.28369799]
 [ 5.01916468  3.66568976  8.50020356 ...  3.19924038  4.92803331
   2.8132085 ]
 [10.83708293 11.31007474  8.07749151 ... 12.62275096 10.98670355
  13.12978707]
 ...
 [ 1.20348111  3.08000879  4.65464122 ...  2.07394209  1.18184114
   2.79400871]
 [10.12452894 11.63037651  3.88854936 ... 10.84133868 10.1163111
  11.67062245]
 [ 9.99671928  8.45783896  9.01838345 ...  8.06798374  9.90973015
   7.749956  ]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [210]:
Z = np.arange(5*5).reshape((5,5))
shape = (3,3)
fill  = 0
position = (3,0)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()

Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]

R[r[0], r[1]] = Z[z[0], z[1]]
print(Z)
print(R)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0 10 11]
 [ 0 15 16]
 [ 0 20 21]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [86]:
#np.info('as_strided')
Z = np.arange(1,15,dtype=np.uint32)
np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       ...,
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★)

In [96]:
Z = np.random.randint(2, size=(5,5))
print(Z)
#np.info('randint')
np.linalg.matrix_rank(Z)

[[1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 0 0 1]
 [1 1 0 1 0]
 [0 0 0 1 0]]


4

#### 83. How to find the most frequent value in an array?

In [99]:
Z = np.random.randint(0,10,10)
print(Z)
np.bincount(Z).argmax()

[4 1 6 5 3 4 1 6 7 7]


1

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [108]:
Z = np.random.randint(0,5,(10,10))
print(Z)
import numpy.lib.stride_tricks as sl
#np.info('sliding_window_view')
sl.sliding_window_view(Z, window_shape=(3, 3))


[[3 2 1 ... 2 4 4]
 [4 2 0 ... 3 4 0]
 [1 2 3 ... 4 3 0]
 ...
 [2 2 4 ... 0 2 2]
 [1 3 0 ... 2 3 3]
 [0 1 1 ... 2 2 1]]


array([[[[3, 2, 1],
         [4, 2, 0],
         [1, 2, 3]],

        [[2, 1, 3],
         [2, 0, 4],
         [2, 3, 3]],

        [[1, 3, 2],
         [0, 4, 0],
         [3, 3, 0]],

        ...,

        [[1, 1, 2],
         [2, 1, 3],
         [2, 3, 4]],

        [[1, 2, 4],
         [1, 3, 4],
         [3, 4, 3]],

        [[2, 4, 4],
         [3, 4, 0],
         [4, 3, 0]]],


       [[[4, 2, 0],
         [1, 2, 3],
         [3, 2, 1]],

        [[2, 0, 4],
         [2, 3, 3],
         [2, 1, 3]],

        [[0, 4, 0],
         [3, 3, 0],
         [1, 3, 0]],

        ...,

        [[2, 1, 3],
         [2, 3, 4],
         [2, 0, 1]],

        [[1, 3, 4],
         [3, 4, 3],
         [0, 1, 0]],

        [[3, 4, 0],
         [4, 3, 0],
         [1, 0, 3]]],


       [[[1, 2, 3],
         [3, 2, 1],
         [3, 2, 3]],

        [[2, 3, 3],
         [2, 1, 3],
         [2, 3, 2]],

        [[3, 3, 0],
         [1, 3, 0],
         [3, 2, 2]],

        ...,

        [[2, 3, 4],
    

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [110]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
S


Symetric([[ 3, 13,  7, 17,  8],
          [13,  5,  4,  9,  7],
          [ 7,  4,  8, 42,  2],
          [17,  9, 42,  3,  4],
          [ 8,  7,  2,  4,  3]])

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [112]:
p, n = 2, 2
M = np.ones((p,n,n))
V = np.ones((p,n,1))
np.tensordot(M, V, axes=[[0, 2], [0, 1]])

array([[4.],
       [4.]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [133]:

Z = np.arange(16*16).reshape((16,16))
print(Z)
sl.sliding_window_view(Z, (4,4))[::4, ::4].sum(axis=(-2,-1))
#np.info('sliding_window_view')

[[  0   1   2 ...  13  14  15]
 [ 16  17  18 ...  29  30  31]
 [ 32  33  34 ...  45  46  47]
 ...
 [208 209 210 ... 221 222 223]
 [224 225 226 ... 237 238 239]
 [240 241 242 ... 253 254 255]]


array([[ 408,  472,  536,  600],
       [1432, 1496, 1560, 1624],
       [2456, 2520, 2584, 2648],
       [3480, 3544, 3608, 3672]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [135]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 1 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [137]:
Z = np.arange(20)
n = 5
print (Z[np.argsort(Z)[-n:]])


[15 16 17 18 19]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [140]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int).reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2], [3], [4, 5], [6, 7])))


[[1 3 4 6]
 [1 3 4 7]
 [1 3 5 6]
 ...
 [2 3 4 7]
 [2 3 5 6]
 [2 3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [141]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
np.core.records.fromarrays(Z.T,
                            names='col1, col2, col3',
                            formats = 'S8, f8, i8')

rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [153]:
Z = np.arange(3)

#print( Z*Z*Z )
#print( np.einsum('i,i,i->i',Z,Z,Z) )
#np.info('einsum')
%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z,Z,Z)

2.78 µs ± 816 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
2.27 µs ± 505 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
5.51 µs ± 1.03 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [157]:
A = np.arange(8*3).reshape((8,3))
B = np.arange(2*2).reshape((2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
np.where(C.any((3,1)).all(1))[0]


array([0])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [164]:
Z = np.random.randint(2, size=(10,3))
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
Z[~E]

#np.info('any')

array([[0, 1, 1],
       [1, 1, 0],
       [1, 0, 0],
       ...,
       [1, 0, 1],
       [0, 1, 1],
       [0, 1, 1]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [175]:
I = np.arange(8, dtype=np.ubyte)
np.unpackbits(I[:, np.newaxis], axis=1)[3:,4:]

array([[0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1]], dtype=uint8)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [181]:
Z = np.random.randint(2,size=(5,2))
print(Z)
np.unique(Z, axis=0)

[[1 1]
 [0 0]
 [1 0]
 [0 1]
 [0 0]]


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [190]:
A = np.random.randint(2,size=5)
B = np.random.randint(2,size=5)
print(A, B)
#np.info('einsum')
print( np.einsum('i->', A) ) #sum
print( np.einsum('i,i->i', A, B) ) # mul
print( np.einsum('i,i', A, B) ) # inner
print( np.einsum('i,j->ij', A, B) ) # outer


[1 1 1 1 1] [1 0 1 1 1]
5
[1 0 1 1 1]
4
[[1 0 1 1 1]
 [1 0 1 1 1]
 [1 0 1 1 1]
 [1 0 1 1 1]
 [1 0 1 1 1]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [191]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [193]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
X[M]


array([[2., 0., 1., 1.]])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [194]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.05266112  0.29498556]
